title: Curso HQ Catalogo
markdown: kramdown
# Set `url` and `baseurl` for a project site hosted at
# https://samuelsbjr97.github.io/SSBJr.HQCourses
url: "https://samuelsbjr97.github.io"
baseurl: "/SSBJr.HQCourses"
permalink: pretty
collections:
  courses:
    output: true
    permalink: /courses/:slug/
# Include assets folder
include:
  - assets
